# Generated by Django 5.1.6 on 2025-02-22 03:23

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=100)),
                (
                    "publication_date",
                    models.DateField(
                        validators=[books.models.validate_publication_date]
                    ),
                ),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("summary", models.TextField()),
            ],
        ),
    ]
